select * from administracion.empleado;
insert into  administracion.Empleado values('ADMIN',1140840913,'Administrador','General',null,'4vHrBgsvH3+FjnuGkNTjtQ==');
insert into  administracion.Empleado values('DESARROLLADOR',1140840913,'Rodolfo Felipe','Pineda','Mejia','4vHrBgsvH3+FjnuGkNTjtQ==');
select * from administracion.perfil;
insert into administracion.perfil values('Administrador','ADMINISTRADOR');
insert into administracion.perfil values('Participante','PARTICIPANTE');
select * from administracion.empleadoperfil;
insert into administracion.empleadoperfil values('ADMIN',1);
insert into administracion.empleadoperfil values('DESARROLLADOR',2);
select * from administracion.Cliente;
insert into administracion.Cliente values(5463217,'Ideaware','Nearshore');
select * from logistica.Producto;
insert into logistica.Producto values('Silla','Para uso oficina',100000);
insert into logistica.Producto values('Mesa','Para uso domestico',200000);
select * from facturacion.Factura;
insert into facturacion.Factura values(1,'DESARROLLADOR',GETDATE());
select * from facturacion.FacturaProducto;
insert into facturacion.FacturaProducto values(2,1,2);
insert into facturacion.FacturaProducto values(2,2,3);